/**
 * Stylesheet for the chat-timeline rail, injected once as a
 * `<style data-plugin-css="chat-timeline">` tag. All classes carry the
 * `dsh-tl-` prefix; colors use the CSS system colors Canvas/CanvasText so the
 * rail follows the app's color-scheme without reaching into DSH theme tokens.
 * Visual constants replicate the ZCode TurnNavigator (spec section 2.2).
 */
export declare const TIMELINE_STYLES = "\n.dsh-tl-nav {\n  position: fixed;\n  z-index: 10;\n  width: 48px;\n  pointer-events: none;\n  opacity: 1;\n  transition: opacity 150ms ease-out;\n}\n.dsh-tl-nav[data-visible=\"false\"] {\n  opacity: 0;\n  visibility: hidden;\n}\n.dsh-tl-scroll {\n  position: absolute;\n  left: 12px;\n  top: 50%;\n  transform: translateY(-50%);\n  width: 36px;\n  max-height: calc(100% - 96px);\n  overflow-x: hidden;\n  overflow-y: auto;\n  padding-block: 4px;\n  pointer-events: auto;\n  scrollbar-width: none;\n  color: CanvasText;\n}\n.dsh-tl-scroll::-webkit-scrollbar {\n  display: none;\n}\n.dsh-tl-track {\n  position: relative;\n  width: 36px;\n}\n.dsh-tl-slot {\n  position: absolute;\n  left: 0;\n  top: 0;\n  height: 10px;\n  width: 36px;\n  padding: 0;\n  border: 0;\n  background: transparent;\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  border-radius: 2px;\n  cursor: pointer;\n}\n.dsh-tl-slot:focus-visible {\n  outline: 2px solid CanvasText;\n  outline-offset: 2px;\n}\n.dsh-tl-tick {\n  display: block;\n  height: 2px;\n  width: 12px;\n  border-radius: 999px;\n  background: currentColor;\n  transform-origin: left center;\n  transition: height 150ms ease-out, opacity 150ms ease-out, transform 150ms ease-out, background-color 150ms ease-out;\n}\n@media (prefers-reduced-motion: reduce) {\n  .dsh-tl-nav,\n  .dsh-tl-tick {\n    transition: none;\n  }\n}\n.dsh-tl-tip {\n  position: fixed;\n  z-index: 60;\n  width: 320px;\n  max-width: calc(100vw - 2rem);\n  padding: 12px;\n  border-radius: 10px;\n  background: Canvas;\n  color: CanvasText;\n  border: 1px solid color-mix(in srgb, CanvasText 15%, transparent);\n  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.35);\n  pointer-events: none;\n}\n.dsh-tl-tip-user {\n  margin: 0;\n  display: -webkit-box;\n  -webkit-box-orient: vertical;\n  -webkit-line-clamp: 2;\n  overflow: hidden;\n  white-space: pre-line;\n  font-size: 13px;\n  line-height: 20px;\n  font-weight: 500;\n}\n.dsh-tl-tip-assistant {\n  margin: 8px 0 0;\n  display: -webkit-box;\n  -webkit-box-orient: vertical;\n  -webkit-line-clamp: 3;\n  overflow: hidden;\n  white-space: pre-line;\n  font-size: 13px;\n  line-height: 20px;\n  opacity: 0.8;\n}\n.dsh-tl-tip-assistant[data-kind=\"running\"],\n.dsh-tl-tip-assistant[data-kind=\"empty\"] {\n  opacity: 0.55;\n}\n";
/** Inject the stylesheet once per document. */
export declare function ensureStyles(doc: Document): void;
